### ISSUE TITLE
Cannot find 'core_m25.dll'...

### ISSUE THREAD

**Issue by tripplowe** [cvBin/UAV-Mapper#1]
On Windows 10...  I am presented with a "Cannot find core_m25.dll.  Please reinstall..." error when I try to run UAV-Mapper.  I wonder if you might be able to give me some insight as to why?

**Comment by cvBin** [comment]
Please check if this file core_m25.dll exists in the folder? If not, please download the latest version.

**Comment by tripplowe** [comment]
Thank you.  I re-downloaded on another machine and I do not receive the error.
